### ISSUE TITLE
Support Application Running in Kubernetes

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/agent#21]
For applications running inside a Kubernetes cluster, we will support identifying applications by pod name or pod name prefix. Kubernetes stores data about the containers (and their pods) running on the node in directories and files under `/var/lib/docker/containers`. The container information points to the correct log file for each pod under `/var/log`. By mounting both these directories into a container, the agent can gain access to all the information it needs to coordinate and tail logs from pods. (This assumes that the applications are writing logs to STDOUT).

The Timber agent should be installed inside of a [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) so that it is launched on every node.

The configuration data will be stored inside a [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configmap/). This isolates configuration from the DaemonSet definition, allowing the user to modify the configuration without modifying the DaemonSet.

## Configuration

The configuration for Kubrenetes is based on pods; users can either gather logs based on the name of the pod or on a name prefix.

The prefix option is essential when dealing with deployments and replicated sets. For any definition `user-registration-app` of a deployment or replicated set, Kubernetes will use `user-registration-app-` as the base name of pods it launches to meet the requested scale. It postfixes a unique string after the base name. So a prefix of `user-registration-app` will pick up `user-registration-app-c5287c88`, `user-registration-app-878bf484`, and `user-registration-app-560da75d`.

Here is an example configuration:

```toml
[[kubernetes_pods]]
prefixes = ["user-registration-app"]
apiKey = "12345"

[[kubernetes_pods]]
prefixes = ["photo-upload-app"]
apiKey = "abcdef"

[[kubernetes_pods]]
names = ["postgres-master"]
prefixes = ["postgres-replica"]
apiKey = "zxcvb"
```
