### ISSUE TITLE
Auto-build on version is broken

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/agent#29]
When a new version tag is created and pushed to the GitHub repo, a new build in CircleCI is not triggered. This is an issue with CircleCI 2.0 not supporting tag-based builds. Until the support is introduced, we need to utilize [a workaround](https://discuss.circleci.com/t/git-tag-deploys-in-2-0/9493/21):

```yaml
deployment:
  release:
    tag: /v.*/
    commands:
      - echo "make tags run in 2.0"
```

There needs to be a corresponding `deploy` step inside a `build` job. The `deploy` step will be run if the tag pattern matches.
