### ISSUE TITLE
Allow API keys to be set using environment variables

### ISSUE THREAD

**Issue by DavidAntaramian** [timberio/agent#36]
Some users, like those on Elastic Beanstalk, will package a configuration file into an immutable package designed to be pushed to multiple machines. In certain cases, this means that the _same_ configuration file must be usable for multiple environments without modification.

In order to allow this, we want to allow API keys to be specified using environment variables. For example:

```toml
[[files]]
path = "/var/log/nginx/ngingx.log"
apiKey = "env:TIMBER_NGINX_API_KEY"

[[files]]
path = "/var/log/node/node.log"
apiKey = "env:TIMBER_NODE_API_KEY"
```

Supersedes #32
