### ISSUE TITLE
Allow the setting of a default API key in the configuration file

### ISSUE THREAD

**Issue by binarylogic** [timberio/agent#74]
Instead of:

```toml
[[files]]
path = "/path/to/file.log"
api_key = "my-api-key"

[[files]]
path = "/path/to/file.log"
api_key = "my-api-key"
```

It would be nice to do:

```toml
api_key = "my-api-key"

[[files]]
path = "/path/to/file.log"

[[files]]
path = "/path/to/file.log"

[[files]]
path = "/path/to/file.log"
api_key = "different-api-key"
```
